WINDOW_WIDTH = 800
WINDOW_HEIGHT = 600
WINDOW_FOV = 90
WINDOW_CLIPPING_NEAR = 0.1
WINDOW_CLIPPING_FAR = 1000.0

HEIGHTMAP_BASE_SEED = 1
HEIGHTMAP_WIDTH = 100
HEIGHTMAP_DEPTH = 100
HEIGHTMAP_SCALE = 10
HEIGHTMAP_OCTAVES = 3
HEIGHTMAP_PERSISTENCE = 0.5
HEIGHTMAP_LACUNARITY = 2.0

# TRACKERS
SIMULATE_EROSION = True     #NEEDS SLIDER
TERRAIN_NEEDS_UPDATE = False
TERRAIN_REGEN_REQ = False

class STATS:
    TRIANGLE_COUNT = 0
    VERTEX_COUNT = 0
    ITER_COUNT = 0
    GEN_TIME = 0.0          # terrain generation time (ms)
    RENDER_TIME = 0.0       # gpu rendering time (ms)
    FRAME_TIME = 0.0        # full frame time (ms)
    FPS = 0