WINDOW_WIDTH = 800
WINDOW_HEIGHT = 600
WINDOW_FOV = 90
WINDOW_CLIPPING_NEAR = 0.1
WINDOW_CLIPPING_FAR = 1000.0

HEIGHTMAP_BASE_SEED = 1
HEIGHTMAP_WIDTH = 100
HEIGHTMAP_DEPTH = 100
HEIGHTMAP_SCALE_DEFAULT = 10
HEIGHTMAP_OCTAVES_DEFAULT = 10
HEIGHTMAP_PERSISTENCE_DEFAULT = 0.5
HEIGHTMAP_LACUNARITY_DEFAULT = 2.0

# TRACKERS
STATS_ITER_COUNT = 0
STATS_TRIANGLE_COUNT = 0